#!/bin/bash
#!/bin/bash
cd "$(dirname "$0")"

# Stash any changes to the working tree
git stash -q --keep-index

function cleanup {
   git stash pop -q
}
trap cleanup EXIT

cargo fmt --all -- --check
cargo clippy --all -- -D warning

exit 0
