[build]
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update",
  "apt-get install -y libsqlite3-dev:$CROSS_DEB_ARCH"
]

[target.x86_64-unknown-linux-gnu]
pre-build = [
  "dpkg --add-architecture amd64",
  "apt-get update",
  "apt-get install -y libsqlite3-dev:amd64"
]

[target.x86_64-unknown-linux-musl]
pre-build = [
  "dpkg --add-architecture amd64",
  "apt-get update",
  "apt-get install -y libsqlite3-dev:amd64"
]