import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
	// Base recommended configs
	js.configs.recommended,
	...tseslint.configs.recommendedTypeChecked,
	prettier,

	// Project-specific settings
	{
		languageOptions: {
			parserOptions: {
				projectService: true,
				tsconfigRootDir: import.meta.dirname,
			},
		},
	},

	// Files to lint
	{
		files: ['src/**/*.ts'],
	},

	// Files to ignore
	{
		ignores: [
			'node_modules/**',
			'dist/**',
			'target/**',
			'*.node',
			'index.js', // Auto-generated by napi-rs
			'index.d.ts', // Auto-generated by napi-rs
			'examples/**', // JavaScript examples, not TypeScript
		],
	},

	// Custom rules matching project style
	{
		rules: {
			// Allow console in tests and examples
			'no-console': 'off',

			// TypeScript-specific adjustments
			'@typescript-eslint/no-unused-vars': [
				'error',
				{
					argsIgnorePattern: '^_',
					varsIgnorePattern: '^_',
				},
			],

			// Allow explicit any in test files
			'@typescript-eslint/no-explicit-any': 'warn',

			// Consistent with Rust's Result/Option patterns
			'@typescript-eslint/no-floating-promises': 'error',
			'@typescript-eslint/await-thenable': 'error',
		},
	},

	// Test files - more lenient rules
	{
		files: ['src/**/*.test.ts'],
		rules: {
			// Test framework handles promises implicitly
			'@typescript-eslint/no-floating-promises': 'off',

			// Test code often needs to work with any types (JSON parsing, etc.)
			'@typescript-eslint/no-unsafe-assignment': 'off',
			'@typescript-eslint/no-unsafe-member-access': 'off',
			'@typescript-eslint/no-unsafe-call': 'off',
			'@typescript-eslint/no-unsafe-argument': 'off',
			'@typescript-eslint/no-unsafe-return': 'off',

			// Allow explicit any in tests
			'@typescript-eslint/no-explicit-any': 'off',
		},
	},
);
