name: Build and release binaries

on:
  push:
    branches:
      - "feat-workflow-release-binaries"
  release:
    types:
      - created
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare:
    name: Prepare release
    runs-on: ubuntu-latest
    outputs:
      release_tag: $RELEASE_TAG
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get release tag
        id: get_release
        run: echo 'RELEASE_TAG=v$(cat Cargo.toml | sed -n "s/^version *= *\"\(.*\)\"/\1/p")' >> $GITHUB_ENV

      - name: Create release if needed
        run: gh release create $RELEASE_TAG || true

  build-linux:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        include:
          - arch: "x86_64"
            libc: "gnu"
          #- arch: "aarch64"
          #  libc: "gnu"
    steps:
      - name: Install aarch64 tools
        if: ${{ contains(matrix.arch, 'aarch64') }}
        run: sudo apt-get install -y binutils-aarch64-linux-gnu

      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}
          default: true

      - name: Install cross
        run: cargo install cross

      - name: Build binary
        run: cross build --release --all-features

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: "versatiles-linux-${{ matrix.arch }}-${{ matrix.libc }}"
          path: "target/release/versatiles"

  build-macos:
    runs-on: macos-latest
    needs: prepare
    strategy:
      matrix:
        include:
          - arch: "x86_64"
          - arch: "aarch64"
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.arch }}-apple-darwin
          default: true

      - name: Build binary
        run: cargo build --release --all-features

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: "versatiles-macos-${{ matrix.arch }}"
          path: "target/release/versatiles"

  build-windows:
    if: false
    runs-on: windows-latest
    needs: prepare
    strategy:
      matrix:
        include:
          - arch: "x86_64"
            libc: "msvc"
          - arch: "aarch64"
            libc: "msvc"
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.arch }}-pc-windows-${{ matrix.libc }}
          default: true

      - name: Build binary
        run: cargo build --release --all-features

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: "versatiles-windows-${{ matrix.arch }}.exe"
          path: "target/release/versatiles.exe"

  upload-release:
    needs:
      - build-linux
      - build-macos
      - build-windows
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      # - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: release

      - name: Upload binary
        run: |
          cd release
          find . -maxdepth 1 -type f -exec echo "sha256sum '{}' > '{}'.sha256" \; | sh
          gh release upload $RELEASE_TAG --clobber *
          # gh release edit $RELEASE_TAG --draft=false --latest --prerelease=false
