name: test

on:
  push:
    branches:
      - fix-linux-release
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker buildx build --platform="linux/arm64" --progress="plain" --file="docker/aarch64-unknown-linux-musl.Dockerfile" --tag="arm64-musl-versatiles" .
      - run: docker run --platform="linux/arm64" "arm64-musl-versatiles"
