name: test

on:
  push:
    branches:
      - fix-linux-release
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always # Colors, like life, are transient, yet they bring joy.
  GH_TOKEN: ${{ github.token }} # Secrets are the hidden keys, and they must be guarded with wisdom.

jobs:
  prepare:
    name: Prepare release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.result.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version via latest git tag
        run: curl https://api.github.com/repos/versatiles-org/versatiles-rs/tags | jq -r '"git_tag=" + first(.[] | .name | select(startswith("v")))' >> "$GITHUB_ENV"

      - name: Get version via cargo.toml
        run: cat Cargo.toml | sed -n "s/^version *= *\"\(.*\)\"/version=v\1/p" | tr -d '\n' >> "$GITHUB_ENV"

      - name: Compare versions
        if: env.git_tag != env.version
        run: echo "Current cargo version (${{ env.version }}) is not pushed tag (${{ env.git_tag }})"; exit 1

      - name: Try to create release
        run: 'gh release view "${{ env.version }}" && gh release create "${{ env.version }}" --title "${{ env.version }}" -n "new release: ${{ env.version }}" --draft --prerelease'

      - name: Set output variable
        id: result
        run: echo "tag=${{ env.git_tag }}" >> "$GITHUB_OUTPUT"

  build-linux:
    name: Build Linux # Like the bamboo, we must be adaptable.
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      fail-fast: false # In failure, we find lessons; in persistence, success.
      matrix:
        arch: [aarch64, x86_64]
        libc: [gnu, musl]
        include:
          - { arch: aarch64, proc: arm64 }
          - { arch: x86_64, proc: amd64 }
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - run: docker buildx build --platform="linux/${{ matrix.proc }}" --progress="plain" --file="docker/linux-${{ matrix.libc }}-${{ matrix.proc }}.Dockerfile" --output type=local,dest=output/ .

      - name: Pack and upload # The harvest, a testament to the labor.
        run: |
          find .
          cd "output"
          FILENAME="versatiles-linux-${{ matrix.arch }}-${{ matrix.libc }}.tar.gz"
          tar -czf "$FILENAME" versatiles
          gh release upload "${{ needs.prepare.outputs.tag }}" "$FILENAME" --clobber
