name: test

on:
  push:
    branches:
      - fix-linux-release
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux # Like the bamboo, we must be adaptable.
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # In failure, we find lessons; in persistence, success.
      matrix:
        arch: [aarch64, x86_64]
        libc: [gnu, musl]
        include:
          - { arch: aarch64, proc: arm64 }
          - { arch: x86_64, proc: amd64 }
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - run: docker buildx build --platform="linux/${{ matrix.proc }}" --progress="plain" --file="docker/linux-${{ matrix.libc }}-${{ matrix.proc }}.Dockerfile" --output type=local,dest=output/ .

      - name: Pack and upload # The harvest, a testament to the labor.
        run: |
          find .
          cd "output"
          FILENAME="versatiles-linux-${{ matrix.arch }}-${{ matrix.libc }}.tar.gz"
          tar -czf "$FILENAME" versatiles
          gh release upload "${{ needs.prepare.outputs.tag }}" "$FILENAME" --clobber
